//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesItems
    {
        public int SaleId { get; set; }
        public int ItemId { get; set; }
        public string Info { get; set; }
    
        public virtual TItems TItems { get; set; }
        public virtual TSales TSales { get; set; }
    }
}
