//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class TItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TItems()
        {
            this.SalesItems = new HashSet<SalesItems>();
        }
    
        public int ItemId { get; set; }
        public int ItemType { get; set; }
        public int ItemMark { get; set; }
        public string ItemName { get; set; }
        public int ItemCount { get; set; }
        public int ItemCost { get; set; }
        public string ItemDetails { get; set; }
        public string ItemInf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesItems> SalesItems { get; set; }
        public virtual TItemsTypes TItemsTypes { get; set; }
        public virtual TMark TMark { get; set; }
    }
}
