//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSales()
        {
            this.SalesItems = new HashSet<SalesItems>();
        }
    
        public int SaleId { get; set; }
        public Nullable<int> SaleClient { get; set; }
        public string SaleDetails { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int SaleUser { get; set; }
        public int SaleCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesItems> SalesItems { get; set; }
        public virtual TClients TClients { get; set; }
        public virtual TUsers TUsers { get; set; }
    }
}
